import { supabase } from '@/lib/supabase';
import type { Cart, CartItem, Product } from '@/types';
import { assertData, assertOk, normalizeError } from './base';

export type CartWithItems = Cart & { items: (CartItem & { product: Product })[] };
export async function getActiveCart(userId: string): Promise<CartWithItems | null> { const { data: cart, error } = await supabase.from('carts').select('*').eq('user_id', userId).eq('status', 'ACTIVE').maybeSingle(); if (error) throw normalizeError(error, 'Unable to load cart.'); if (!cart) return null; const { data: items, error: itemError } = await supabase.from('cart_items').select('*, product:products(*)').eq('cart_id', cart.id).order('created_at'); if (itemError) throw normalizeError(itemError, 'Unable to load cart items.'); return { ...(cart as Cart), items: ((items || []) as (CartItem & { product: Product })[]) }; }
export async function ensureCart(userId: string) { const current = await getActiveCart(userId); if (current) return current; const { data, error } = await supabase.from('carts').insert({ user_id: userId, status: 'ACTIVE' }).select().single(); return assertData(data as Cart | null, error, 'Unable to create cart.'); }
export async function addCartItem(userId: string, productId: string, quantity = 1) { const cart = await ensureCart(userId); const { data: product, error: productError } = await supabase.from('products').select('id,stock_quantity,price').eq('id', productId).eq('is_active', true).single(); const checked = assertData(product as Pick<Product, 'id' | 'stock_quantity' | 'price'> | null, productError, 'Product is unavailable.'); const { data: existing, error: existingError } = await supabase.from('cart_items').select('id,quantity').eq('cart_id', cart.id).eq('product_id', productId).maybeSingle(); if (existingError) throw normalizeError(existingError, 'Unable to check cart item.'); const nextQuantity = (existing?.quantity || 0) + quantity; if (nextQuantity > checked.stock_quantity) throw new Error(`Only ${checked.stock_quantity} item(s) available.`); if (existing) { const { data, error } = await supabase.from('cart_items').update({ quantity: nextQuantity, price_at_time: checked.price }).eq('id', existing.id).select('*, product:products(*)').single(); return assertData(data as CartItem | null, error, 'Unable to update cart.'); } const { data, error } = await supabase.from('cart_items').insert({ cart_id: cart.id, product_id: productId, quantity, price_at_time: checked.price }).select('*, product:products(*)').single(); return assertData(data as CartItem | null, error, 'Unable to add item to cart.'); }
export async function updateCartItem(itemId: string, quantity: number) { if (quantity < 1) return removeCartItem(itemId); const { data: item, error: itemError } = await supabase.from('cart_items').select('id,product:products(stock_quantity),price_at_time').eq('id', itemId).single(); const checked = assertData(item as { id: string; product: { stock_quantity: number }; price_at_time: number } | null, itemError, 'Cart item not found.'); if (quantity > checked.product.stock_quantity) throw new Error(`Only ${checked.product.stock_quantity} item(s) available.`); const { data, error } = await supabase.from('cart_items').update({ quantity }).eq('id', itemId).select('*, product:products(*)').single(); return assertData(data as CartItem | null, error, 'Unable to update cart.'); }
export async function removeCartItem(itemId: string) { const { error } = await supabase.from('cart_items').delete().eq('id', itemId); assertOk(error, 'Unable to remove cart item.'); }
