import { supabase } from '@/lib/supabase';
import type { Address, Profile } from '@/types';
import { assertData, assertOk } from './base';

export async function getMyProfile() { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return null; const { data, error } = await supabase.from('profiles').select('*').eq('id', auth.user.id).single(); return assertData(data as Profile | null, error, 'Unable to load profile.'); }
export async function updateMyProfile(changes: Pick<Profile, 'full_name' | 'phone'>) { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) throw new Error('You must be signed in.'); const { data, error } = await supabase.from('profiles').update(changes).eq('id', auth.user.id).select().single(); return assertData(data as Profile | null, error, 'Unable to update profile.'); }
export async function listMyAddresses() { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return []; const { data, error } = await supabase.from('addresses').select('*').eq('user_id', auth.user.id).order('is_default', { ascending: false }).order('created_at'); return assertData((data as Address[]) || [], error, 'Unable to load addresses.'); }
export async function createAddress(address: Omit<Address, 'id' | 'user_id' | 'created_at' | 'updated_at'>) { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) throw new Error('You must be signed in.'); const { data, error } = await supabase.from('addresses').insert({ ...address, user_id: auth.user.id }).select().single(); return assertData(data as Address | null, error, 'Unable to save address.'); }
export async function deleteAddress(id: string) { const { error } = await supabase.from('addresses').delete().eq('id', id); assertOk(error, 'Unable to delete address.'); }
export async function setDefaultAddress(id: string) { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) throw new Error('You must be signed in.'); await supabase.from('addresses').update({ is_default: false }).eq('user_id', auth.user.id); const { data, error } = await supabase.from('addresses').update({ is_default: true }).eq('id', id).eq('user_id', auth.user.id).select().single(); return assertData(data as Address | null, error, 'Unable to set default address.'); }
