import { useEffect, useState } from 'react';
import { Heart, ShoppingCart, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/auth';
import { addCartItem } from '@/services/cart';
import { listWishlist, removeFromWishlist } from '@/services/wishlist';
import type { WishlistItem } from '@/types';

export default function Wishlist() { const [items, setItems] = useState<WishlistItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [userId, setUserId] = useState('');
  const load = async () => { const { data } = await supabase.auth.getUser(); if (!data.user) return; setUserId(data.user.id); try { setItems(await listWishlist(data.user.id)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load wishlist.'); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
  const remove = async (productId: string) => { try { await removeFromWishlist(userId, productId); setItems((current) => current.filter((item) => item.product_id !== productId)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to remove item.'); } };
  const cart = async (item: WishlistItem) => { try { await addCartItem(userId, item.product_id, 1); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to add item to cart.'); } };
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Saved for later</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Wishlist</h1><p className="mt-1 text-slate-500">Keep products you are considering close at hand.</p></div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading ? <div className="py-20 text-center text-slate-500">Loading wishlist…</div> : !items.length ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-20 text-center"><Heart className="mx-auto text-slate-300" size={42}/><h2 className="mt-4 font-semibold text-slate-900">Your wishlist is empty</h2><Link to="/customer/products" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white">Explore products</Link></div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><Link to={`/customer/products/${item.product_id}`}><div className="aspect-[4/3] bg-slate-100">{item.product?.image_url && <img src={item.product.image_url} alt={item.product.name} loading="lazy" className="h-full w-full object-cover"/>}</div></Link><div className="p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-slate-900">{item.product?.name}</h2><p className="mt-1 font-semibold text-slate-700">{formatCurrency(Number(item.product?.price || 0))}</p></div><button onClick={() => void remove(item.product_id)} aria-label={`Remove ${item.product?.name} from wishlist`} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={17}/></button></div><button onClick={() => void cart(item)} disabled={!item.product?.stock_quantity} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-semibold text-white hover:bg-slate-800 disabled:bg-slate-300"><ShoppingCart size={16}/> {item.product?.stock_quantity ? 'Add to cart' : 'Out of stock'}</button></div></article>)}</div>}</div>;
}
