import { useEffect, useState } from 'react';
import { BarChart3, Users, Package, ShoppingCart, TrendingUp } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/auth';

type Day = { day: string; revenue: number };
type Metrics = { revenue: number; orders: number; customers: number; products: number; aov: number; sold: number };
const emptyMetrics: Metrics = { revenue: 0, orders: 0, customers: 0, products: 0, aov: 0, sold: 0 };

export default function AdminAnalytics() {
  const [metrics, setMetrics] = useState(emptyMetrics); const [trend, setTrend] = useState<Day[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { async function load() {
    const results = await Promise.all([
      supabase.from('orders').select('id,total,created_at').eq('status', 'DELIVERED').order('created_at', { ascending: true }),
      supabase.from('profiles').select('id', { count: 'exact', head: true }).eq('role', 'CUSTOMER'),
      supabase.from('products').select('id', { count: 'exact', head: true }).eq('is_active', true),
      supabase.from('order_items').select('quantity,orders!inner(status)').eq('orders.status', 'DELIVERED'),
    ]); const failure = results.find((r) => r.error); if (failure?.error) { setError(failure.error.message); setLoading(false); return; }
    const orders = results[0].data ?? []; const revenue = orders.reduce((sum, order) => sum + Number(order.total), 0); const grouped = orders.reduce<Record<string, Day>>((acc, order) => { const day = new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric' }).format(new Date(order.created_at)); acc[day] ??= { day, revenue: 0 }; acc[day].revenue += Number(order.total); return acc; }, {});
    setMetrics({ revenue, orders: orders.length, customers: results[1].count ?? 0, products: results[2].count ?? 0, aov: orders.length ? revenue / orders.length : 0, sold: (results[3].data ?? []).reduce((sum, item) => sum + Number(item.quantity), 0) }); setTrend(Object.values(grouped).slice(-14)); setLoading(false);
  } void load(); }, []);
  const cards = [{ label: 'Revenue', value: formatCurrency(metrics.revenue), icon: TrendingUp, tone: 'bg-emerald-50 text-emerald-700' }, { label: 'Delivered orders', value: metrics.orders, icon: ShoppingCart, tone: 'bg-blue-50 text-blue-700' }, { label: 'Customers', value: metrics.customers, icon: Users, tone: 'bg-violet-50 text-violet-700' }, { label: 'Active products', value: metrics.products, icon: Package, tone: 'bg-amber-50 text-amber-700' }];
  if (loading) return <div className="flex min-h-96 items-center justify-center text-slate-500">Loading live analytics…</div>;
  return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Business intelligence</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Analytics</h1><p className="mt-1 text-slate-500">A live view of completed commerce activity from Supabase.</p></div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Unable to load analytics: {error}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`mb-5 flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon size={20} /></div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums text-slate-900">{value}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-semibold text-slate-900">Revenue trend</h2><p className="text-sm text-slate-500">Delivered orders by day</p></div><BarChart3 className="text-slate-400" size={20} /></div><div className="mt-6 h-72">{trend.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={trend}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="day" tick={{ fontSize: 12 }} tickLine={false} axisLine={false} /><YAxis tick={{ fontSize: 12 }} tickLine={false} axisLine={false} /><Tooltip formatter={(value: number) => formatCurrency(value)} /><Bar dataKey="revenue" fill="#2563eb" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-slate-400">No delivered orders yet.</div>}</div></section><section className="rounded-2xl border border-slate-200 bg-slate-900 p-5 text-white shadow-sm"><p className="text-sm text-slate-400">Operational snapshot</p><div className="mt-8 space-y-7"><div><p className="text-sm text-slate-400">Average order value</p><p className="mt-1 text-3xl font-bold">{formatCurrency(metrics.aov)}</p></div><div><p className="text-sm text-slate-400">Products sold</p><p className="mt-1 text-3xl font-bold">{metrics.sold}</p></div><div className="border-t border-slate-700 pt-5 text-sm text-slate-400">Metrics use records marked <span className="font-semibold text-emerald-400">DELIVERED</span>.</div></div></section></div></div>;
}
