import { useEffect, useState } from 'react';
import { ClipboardList, RefreshCw } from 'lucide-react';
import { listAuditLogs } from '@/services/audit';
import { formatDateTime } from '@/lib/auth';
import type { AuditLog } from '@/types';

export default function AdminAuditLogs() {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { setLogs(await listAuditLogs()); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load audit logs.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Governance</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Audit logs</h1><p className="mt-1 text-slate-500">A read-only trail of sensitive account and commerce changes.</p></div><button onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50"><RefreshCw size={16} /> Refresh</button></div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Action</th><th className="px-5 py-4">Target</th><th className="px-5 py-4">Details</th><th className="px-5 py-4">Time</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={4} className="px-5 py-14 text-center text-slate-500">Loading audit trail…</td></tr> : logs.length ? logs.map((log) => <tr key={log.id} className="hover:bg-slate-50"><td className="px-5 py-4"><span className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700"><ClipboardList size={13} /> {log.action.replace(/_/g, ' ')}</span></td><td className="px-5 py-4 text-sm text-slate-600">{log.target_type || 'System'}<span className="block max-w-44 truncate font-mono text-xs text-slate-400">{log.target_id || '—'}</span></td><td className="max-w-xs px-5 py-4 font-mono text-xs text-slate-500">{log.details ? JSON.stringify(log.details) : '—'}</td><td className="px-5 py-4 text-sm text-slate-500">{formatDateTime(log.created_at)}</td></tr>) : <tr><td colSpan={4} className="px-5 py-14 text-center text-slate-500">No audit activity recorded yet.</td></tr>}</tbody></table></div></div></div>;
}
