import { useEffect, useState } from 'react';
import { Check, RefreshCw, Trash2, X } from 'lucide-react';
import { deleteReview, listAllReviews, moderateReview } from '@/services/reviews';
import type { Review } from '@/types';

export default function AdminReviews() { const [items, setItems] = useState<Review[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
 const load = async () => { setLoading(true); try { setItems(await listAllReviews()); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load reviews.'); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
 const approve = async (item: Review, value: boolean) => { try { const updated = await moderateReview(item.id, value); setItems((current) => current.map((row) => row.id === item.id ? { ...row, ...updated } : row)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to moderate review.'); } };
 const remove = async (id: string) => { if (!window.confirm('Delete this review permanently?')) return; try { await deleteReview(id); setItems((current) => current.filter((item) => item.id !== id)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete review.'); } };
 return <div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Customer trust</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Review moderation</h1><p className="mt-1 text-slate-500">Keep product feedback useful, respectful, and visible to customers.</p></div><button onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold"><RefreshCw size={16}/> Refresh</button></div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Review</th><th className="px-5 py-4">Rating</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={4} className="p-10 text-center text-slate-500">Loading reviews…</td></tr> : !items.length ? <tr><td colSpan={4} className="p-10 text-center text-slate-500">No reviews submitted yet.</td></tr> : items.map((item) => <tr key={item.id}><td className="max-w-md px-5 py-4"><p className="font-semibold text-slate-900">{(item as any).products?.name || 'Product review'}</p><p className="mt-1 text-sm text-slate-600">{item.review_text || 'No written comment.'}</p></td><td className="px-5 py-4 font-bold text-amber-600">{item.rating}/5</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.is_approved !== false ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{item.is_approved !== false ? 'Published' : 'Hidden'}</span></td><td className="px-5 py-4 text-right"><button onClick={() => void approve(item, item.is_approved === false)} aria-label={item.is_approved === false ? 'Publish review' : 'Hide review'} className="mr-3 inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50">{item.is_approved === false ? <Check size={16}/> : <X size={16}/>}</button><button onClick={() => void remove(item.id)} aria-label="Delete review" className="inline-flex h-9 w-9 items-center justify-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></div></div>;
}
